WIP: Paypal config endpoint
Syncano/syncano-socket-paypal-config pull request #1
Opened 2018-02-28 11:28 UTC by andela-eshaibu

2018-03-28 09:27 UTC, andela-eshaibu commented
@syncano/cli added as a dependency

2018-03-28 13:22 UTC, adamwardecki requested changes

2018-03-28 13:22 UTC, adamwardecki commented on socket.yml
> +    description: Install AWS config on instance.
It's not an AWS socket ;)

2018-03-28 13:22 UTC, adamwardecki commented on src/install.js
> +    const checkInstallation = await data.paypal_config.first();
try to use `updateOrCreate` here instead of `first`

2018-03-28 13:22 UTC, adamwardecki commented on src/install.js
> +  } catch ({ details, status, message }) {
try to handle the catch in a less verbose way, like in the paypal payment socket: 

```
catch ({ error, statusCode, ...errorDetails }) {
   return response.json(error || errorDetails, statusCode || 400);
}
```

2018-03-28 14:26 UTC, adamwardecki commented on src/install.js
> +    const paypalId = await data.paypal_config.firstOrCreate({}, {});
why not `updateOrCreate` ?

2018-03-29 05:28 UTC, andela-eshaibu commented on src/install.js
> +    const paypalId = await data.paypal_config.firstOrCreate({}, {});
done 👍

2018-04-04 08:11 UTC, adamwardecki requested changes

2018-04-04 08:11 UTC, adamwardecki commented on src/install.js
> +    await data.paypal_config.updateOrCreate({},
first param here should be `{ paypalId.id }`. Please confirm with the docs and change if necessary

2018-04-04 09:26 UTC, andela-eshaibu commented on src/install.js
> +    await data.paypal_config.updateOrCreate({},
We can't do `{ paypalId.id }` since we can't tell the id. And since its expected to create if data table empty or update it based on any condition.

2018-04-16 13:32 UTC, adamwardecki commented on src/install.js
> +    await data.paypal_config.updateOrCreate({},
The thing is that with the `updateOrCreate` method, if the first param is an empty object than It will always create a new one. Because there's no criteria to test for in case of potential update. And we want to check if there's an object that already contains the paypal config data. Am I right?

2018-04-16 13:52 UTC, eshaibu commented on src/install.js
> +    await data.paypal_config.updateOrCreate({},
No, it does not create a new one

2018-04-17 11:12 UTC, adamwardecki commented on src/install.js
> +    await data.paypal_config.updateOrCreate({},
ok

2018-04-17 11:12 UTC, adamwardecki approved these changes

2018-04-17 11:12 UTC, merged